### ISSUE TITLE
[FEATURE] PRAI CRI

### ISSUE THREAD

**Issue by Solarixz** [alexandredpy/PRAIbot#1]
**Describe the solution you'd like**
BONJOUR J'AIMERAIS POUVOIR UTILISER LA COMMANDE "!prai cri".
CETTE COMMANDE VA SERVIR A APPELER LA COMMANDE "/tts pérai" AFIN DE CRIER PRAI CHEZ TOUT LE MONDE

**Additional context**
JE LAISSE A VOTRE MAIN LE CHOIX DU MOT CLE DERRIERE !PRAI
MERCI LA ZONE

**Comment by alexandredpy** [comment]
Hello MLAM,

I have noted your feature request, thanks for your energy in this project.
I will work on this feature, and I will keep you in touch when it will be ready.

Regards,
Alexandre
_Project Owner_

**Comment by alexandredpy** [comment]
This documentation should be helpful https://stackoverflow.com/questions/59959147/discord-py-text-to-speech-module
